'use client';

import { useState } from 'react';
import { CheckCircle2, FileSpreadsheet, Upload, XCircle } from 'lucide-react';

export default function ImportsPage() {
  const [batch, setBatch] = useState<{ fileName: string; rowCount: number; successCount: number; errorCount: number } | null>(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  async function upload(file: File | undefined) { if (!file) return; setBusy(true); setMessage('正在读取工作表并执行预览校验…'); const form = new FormData(); form.append('file', file); const res = await fetch('/api/imports/preview', { method: 'POST', body: form }); const json = await res.json(); setBatch(json.batch); setMessage(json.batch ? `批次 ${json.batch.id} 已生成，确认后才会进入业务草稿。` : json.message); setBusy(false); }
  return <main className="content"><div className="page-heading"><div><div className="eyebrow">Imports / Excel Data</div><h1>Excel 数据批次</h1><p className="lede">从标准模板开始建立多站点数据底座，导入不会直接覆盖已生效数据。</p></div><div className="top-actions"><a className="btn" href="/sample-data/船舶计划模板.xlsx" download><FileSpreadsheet size={14} /> 下载模板</a></div></div><div className="dashboard-grid"><div className="panel"><div className="panel-header"><div><div className="panel-title">上传并预览</div><div className="panel-kicker">支持站点、人员、资质、班次、船舶计划和执行反馈模板</div></div></div><div className="panel-body"><label htmlFor="excel-file" className="upload-zone"><Upload size={24} color="#0d5962" /><strong>{busy ? '正在校验…' : '选择 Excel 文件'}</strong><span>支持 .xlsx / .xls · 先预览，后确认导入</span><input id="excel-file" type="file" accept=".xlsx,.xls" onChange={(e) => upload(e.target.files?.[0])} hidden /></label>{message && <div className="notice" style={{ marginTop: 15 }}>{message}</div>}</div></div><div className="panel"><div className="panel-header"><div><div className="panel-title">导入规则</div><div className="panel-kicker">数据问题不会被静默吞掉</div></div></div><div className="panel-body"><div className="audit-item"><CheckCircle2 size={15} color="#0d5962" /><div><div className="audit-main">预览后生成草稿批次</div><div className="audit-time">确认前不影响有效计划</div></div></div><div className="audit-item"><XCircle size={15} color="#d8703f" /><div><div className="audit-main">错误行单独输出</div><div className="audit-time">包含行号、字段、原始值和修正建议</div></div></div><div className="audit-item"><FileSpreadsheet size={15} color="#697582" /><div><div className="audit-main">同批次可回退</div><div className="audit-time">保留原始文件和导入责任人</div></div></div></div></div></div>{batch && <div className="panel" style={{ marginTop: 17 }}><div className="panel-header"><div><div className="panel-title">最新预览批次</div><div className="panel-kicker">{batch.fileName}</div></div><span className="tag tag-risk">待确认</span></div><div className="panel-body"><div className="metric-grid" style={{ gridTemplateColumns: 'repeat(3, minmax(0,1fr))', marginBottom: 0 }}><div className="metric"><div className="metric-top">总行数</div><div className="metric-value">{batch.rowCount}</div></div><div className="metric"><div className="metric-top">可导入</div><div className="metric-value">{batch.successCount}</div></div><div className="metric"><div className="metric-top">错误/空行</div><div className="metric-value">{batch.errorCount}</div></div></div></div></div>}</main>;
}
