'use client';

import { useState } from 'react';
import { RefreshCw, Send } from 'lucide-react';
import { store } from '@/lib/store';
import { useRouter } from 'next/navigation';

export function ChangeForm() {
  const router = useRouter(); const [open, setOpen] = useState(false); const [taskId, setTaskId] = useState(store.tasks[0]?.id ?? ''); const [type, setType] = useState('延误'); const [afterValue, setAfterValue] = useState('计划开始时间顺延 60 分钟'); const [reason, setReason] = useState('船舶预计到港时间变化'); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); const response = await fetch('/api/changes', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ taskId, type, afterValue, reason }) }); const json = await response.json(); setMessage(json.message ?? `已登记变更 ${json.id}`); setBusy(false); setOpen(false); router.refresh(); }
  return <>{open ? <form className="panel" style={{ padding: 17, width: 360, position: 'absolute', right: 0, top: 46, zIndex: 5, boxShadow: '0 18px 50px rgba(22,32,42,.14)' }} onSubmit={submit}><div className="panel-title">登记计划变更</div><div className="login-field"><label>任务</label><select className="select" style={{ width: '100%' }} value={taskId} onChange={(e) => setTaskId(e.target.value)}>{store.tasks.slice(0, 20).map((task) => <option value={task.id} key={task.id}>{task.taskNo} · {task.vesselName}</option>)}</select></div><div className="login-field"><label>变更类型</label><select className="select" style={{ width: '100%' }} value={type} onChange={(e) => setType(e.target.value)}><option>延误</option><option>取消</option><option>提前</option><option>插单</option><option>人员不可用</option><option>人工换班</option></select></div><div className="login-field"><label>变更后信息</label><input className="input" value={afterValue} onChange={(e) => setAfterValue(e.target.value)} /></div><div className="login-field"><label>原因</label><input className="input" value={reason} onChange={(e) => setReason(e.target.value)} /></div><div className="top-actions" style={{ marginTop: 17 }}><button type="button" className="btn" onClick={() => setOpen(false)}>取消</button><button className="btn btn-signal" disabled={busy}><Send size={13} /> {busy ? '登记中' : '登记变更'}</button></div></form> : <button className="btn btn-signal" onClick={() => setOpen(true)}><Send size={14} /> 登记计划变更</button>}{message && <div className="notice" style={{ position: 'fixed', right: 24, bottom: 24, zIndex: 20 }}>{message} <RefreshCw size={12} style={{ marginLeft: 8, verticalAlign: 'middle' }} /></div>}</>;
}
