import Link from 'next/link';
import { ArrowUpRight, CheckCircle2, CircleAlert, FileSpreadsheet, Filter, History, Plus, RefreshCw, RotateCcw, ShieldAlert, UsersRound } from 'lucide-react';
import { store } from '@/lib/store';
import { ChangeForm } from './change-form';

export function PlansPage() {
  const tasks = store.tasks.slice(0, 16);
  return <Page title="计划与任务" eyebrow="Plans / Tasks" description="按站点和计划版本管理引航任务，所有变更可追溯。" actions={<><Link className="btn" href="/imports"><FileSpreadsheet size={14} /> Excel 批次</Link><button className="btn btn-primary"><Plus size={14} /> 新建计划</button></>}><div className="filter-bar"><Filter size={14} /><span className="filter-label">视图</span><select className="select"><option>未来 72 小时</option></select><select className="select"><option>全部站点</option>{store.stations.map((s) => <option key={s.id}>{s.name}</option>)}</select><span className="tag tag-muted">已加载 DEMO 批次</span></div><div className="panel"><div className="panel-header"><div><div className="panel-title">任务计划池</div><div className="panel-kicker">共 {store.tasks.length} 项 · 当前展示首批任务</div></div><span className="tag">版本 P-20260831-01</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>任务</th><th>站点 / 水域</th><th>计划时间</th><th>类型</th><th>优先级</th><th>状态</th><th>操作</th></tr></thead><tbody>{tasks.map((task) => <tr key={task.id}><td><strong>{task.vesselName}</strong><div className="muted">{task.taskNo}</div></td><td>{task.stationName}<div className="muted">{task.area}</div></td><td>{new Date(task.startsAt).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })}<div className="muted">至 {new Date(task.endsAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</div></td><td>{task.type}</td><td><span className={`tag ${task.priority !== '普通' ? 'tag-warn' : 'tag-muted'}`}>{task.priority}</span></td><td><span className={`tag ${task.dataQuality === '待补充' ? 'tag-warn' : ''}`}>{task.dataQuality === '待补充' ? '数据待补' : task.status}</span></td><td><button className="btn btn-quiet" title="查看任务"><ArrowUpRight size={13} /></button></td></tr>)}</tbody></table></div></div></Page>;
}

export function PeoplePage() { return <Page title="人员与资质" eyebrow="Resources / Qualifications" description="集中维护人员归属、可用性、资质能力与班次状态。" actions={<button className="btn btn-primary"><Plus size={14} /> 新增人员</button>}><div className="metric-grid" style={{ gridTemplateColumns: 'repeat(4, minmax(0,1fr))' }}><Metric icon={<UsersRound size={15} />} label="人员总数" value={store.pilots.length} note="6 个站点资源台账" /><Metric icon={<CheckCircle2 size={15} />} label="当前可用" value={store.pilots.filter((p) => p.status === '可用').length} note="可进入候选集合" /><Metric icon={<CircleAlert size={15} />} label="临时不可用" value={store.pilots.filter((p) => p.status !== '可用').length} note="请假 / 培训 / 不可用" /><Metric icon={<ShieldAlert size={15} />} label="待核资质" value={12} note="需要管理员确认" warn /></div><div className="panel"><div className="panel-header"><div><div className="panel-title">人员资源台账</div><div className="panel-kicker">默认按人员归属站点隔离，跨站调派需要授权</div></div><div className="top-actions"><select className="select"><option>全部站点</option>{store.stations.map((s) => <option key={s.id}>{s.name}</option>)}</select><button className="btn btn-quiet"><Filter size={13} /> 筛选</button></div></div><div className="table-wrap"><table className="data-table"><thead><tr><th>引航员</th><th>归属站点</th><th>等级</th><th>班组</th><th>今日负荷</th><th>状态</th><th>资质概览</th></tr></thead><tbody>{store.pilots.slice(0, 18).map((pilot) => <tr key={pilot.id}><td><strong>{pilot.name}</strong><div className="muted">{pilot.employeeNo}</div></td><td>{store.stations.find((s) => s.id === pilot.stationId)?.name}</td><td><span className="tag">{pilot.level} 级</span></td><td>{pilot.team}</td><td>{pilot.tasksToday} 项 / {Math.round(pilot.workMinutesToday / 60)}h</td><td><span className={`tag ${pilot.status !== '可用' ? 'tag-warn' : ''}`}>{pilot.status}</span></td><td><span className="muted">{pilot.waters.slice(0, 2).join('、')} 等</span></td></tr>)}</tbody></table></div></div></Page>; }

export function RulesPage() { return <Page title="规则中心" eyebrow="Rules / Governance" description="规则先于模型，业务规则在生效前必须经过模拟和确认。" actions={<button className="btn btn-primary"><Plus size={14} /> 新建规则草案</button>}><div className="notice" style={{ marginBottom: 16 }}><strong>规则状态提醒：</strong>演示环境中的“最低休息时间”仍处于待业务确认状态，当前仅作为风险提示，不代表真实引航制度。</div><div className="panel"><div className="panel-header"><div><div className="panel-title">规则版本与治理状态</div><div className="panel-kicker">每个排班方案都绑定规则版本</div></div><span className="tag">生效 2 · 待确认 2 · 模拟中 1</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>规则</th><th>层级</th><th>适用范围</th><th>当前值</th><th>状态</th><th>来源 / 版本</th><th>操作</th></tr></thead><tbody>{store.rules.map((rule) => <tr key={rule.id}><td><strong>{rule.name}</strong><div className="muted">{rule.id}</div></td><td><span className={`tag ${rule.level === '硬约束' ? 'tag-warn' : ''}`}>{rule.level}</span></td><td>{rule.stationName}</td><td>{rule.value}</td><td><span className={`tag ${rule.status !== '已生效' ? 'tag-risk' : ''}`}>{rule.status}</span></td><td>{rule.source}<div className="muted">{rule.version}</div></td><td><button className="btn btn-quiet" title="模拟规则"><RotateCcw size={13} /></button></td></tr>)}</tbody></table></div></div></Page>; }

export function ChangesPage() { return <Page title="变更与重排" eyebrow="Changes / Replanning" description="集中处理延误、取消、插单、请假和人工换班，默认保护已锁定任务。" actions={<div style={{ position: 'relative' }}><ChangeForm /></div>}><div className="metric-grid" style={{ gridTemplateColumns: 'repeat(4, minmax(0,1fr))' }}><Metric icon={<CircleAlert size={15} />} label="待处理" value={store.changes.filter((c) => c.status === '待处理').length + 4} note="需要调度员处理" warn /><Metric icon={<RefreshCwIcon />} label="处理中" value={1} note="局部重排计算中" /><Metric icon={<CheckCircle2 size={15} />} label="今日完成" value={12} note="已关闭变更" /><Metric icon={<LockIcon />} label="锁定任务" value={3} note="不会自动覆盖" /></div><div className="panel"><div className="panel-header"><div><div className="panel-title">变更事件</div><div className="panel-kicker">所有事件均保留前后值和处理原因</div></div></div><div className="panel-body">{store.changes.length ? store.changes.map((change) => <div className="status-row" key={change.id}><div><div className="status-name">{change.taskNo} · {change.type}</div><div className="status-meta">{change.reason}</div></div><div><span className={`tag ${change.status !== '已完成' ? 'tag-risk' : ''}`}>{change.status}</span></div><div className="status-number">{new Date(change.createdAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</div></div>) : <div className="empty">暂无变更事件。可从任务详情登记延误或插单。</div>}</div></div></Page>; }

export function AuditPage() { return <Page title="审计复盘" eyebrow="Audit / Review" description="查看排班版本、人工调整、审批发布和数据批次，支持并行试运行复盘。" actions={<button className="btn"><History size={14} /> 导出复盘</button>}><div className="panel"><div className="panel-header"><div><div className="panel-title">操作审计</div><div className="panel-kicker">当前演示会话的最近操作记录</div></div><span className="tag tag-muted">只读</span></div><div className="panel-body">{store.audits.length ? store.audits.map((item) => <div className="audit-item" key={item.id}><div className="audit-dot" /><div><div className="audit-main">{item.action} · {item.objectType}</div><div className="audit-time">{item.actor} · {new Date(item.createdAt).toLocaleString('zh-CN')} · {item.detail}</div></div></div>) : <div className="empty">生成方案或导入批次后，这里会出现可追溯的审计记录。</div>}</div></div></Page>; }

function Page({ title, eyebrow, description, actions, children }: { title: string; eyebrow: string; description: string; actions?: React.ReactNode; children: React.ReactNode }) { return <main className="content"><div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p className="lede">{description}</p></div><div className="top-actions">{actions}</div></div>{children}</main>; }
function Metric({ icon, label, value, note, warn = false }: { icon: React.ReactNode; label: string; value: number; note: string; warn?: boolean }) { return <div className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon" style={warn ? { color: '#a84e28', background: '#fff0e8' } : undefined}>{icon}</span></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>; }
function RefreshCwIcon() { return <RefreshCw size={15} />; }
function LockIcon() { return <ShieldAlert size={15} />; }
