import Link from 'next/link';
import { AlertTriangle, ArrowUpRight, CalendarClock, CheckCircle2, Clock3, Database, GitCompareArrows, UsersRound } from 'lucide-react';
import { dashboard } from '@/lib/store';

function shortTime(value: string) { return new Date(value).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' }); }

export default function DashboardPage() {
  const data = dashboard();
  return <main className="content"><div className="page-heading"><div><div className="eyebrow">周一 · 8 月 31 日 · 运行总览</div><h1>今天的引航计划，先处理高风险项</h1><p className="lede">数据截至 {data.lastUpdated}，当前覆盖 {data.stationCount} 个站点和 {data.pilotCount} 名引航员。</p></div><div className="top-actions"><Link className="btn" href="/plans"><Database size={14} /> 导入计划</Link><Link className="btn btn-primary" href="/schedule"><GitCompareArrows size={14} /> 生成候选排班</Link></div></div>
    <section className="metric-grid"><Metric icon={<CalendarClock size={15} />} label="今日任务" value={data.taskCount} note="未来 72 小时计划池" /><Metric icon={<Clock3 size={15} />} label="待排任务" value={data.openCount} note="需要调度员处理" /><Metric icon={<AlertTriangle size={15} />} label="硬冲突 / 风险" value={data.conflictCount} note="含数据质量待补充" warn /><Metric icon={<UsersRound size={15} />} label="可用引航员" value={data.pilotCount - 8} note="当前资源台账" /><Metric icon={<CheckCircle2 size={15} />} label="待确认" value={data.unconfirmedCount} note="等待人工确认发布" /></section>
    <section className="dashboard-grid"><div className="panel"><div className="panel-header"><div><div className="panel-title">重点任务</div><div className="panel-kicker">按优先级和时间排序 · 点击进入排班工作台</div></div><Link className="btn btn-quiet" href="/schedule">查看全部 <ArrowUpRight size={13} /></Link></div><div className="panel-body"><div className="task-list">{data.hotTasks.map((task) => <div className="task-row" key={task.id}><div className="task-time">{shortTime(task.startsAt)}</div><div><div className="task-name">{task.vesselName} · {task.type}</div><div className="task-detail">{task.stationName} / {task.area} · {task.taskNo}</div></div><span className={`tag ${task.priority === '紧急' ? 'tag-warn' : 'tag-risk'}`}>{task.priority}</span><span className={`tag ${task.dataQuality === '待补充' ? 'tag-warn' : 'tag-muted'}`}>{task.dataQuality === '待补充' ? '数据待补' : task.status}</span></div>)}</div></div></div><div className="side-stack"><div className="panel"><div className="panel-header"><div><div className="panel-title">人员负荷</div><div className="panel-kicker">按今日预计作业时长</div></div><Link className="btn btn-quiet" href="/people">人员台账</Link></div><div className="panel-body">{data.pilots.map((pilot) => <div className="status-row" key={pilot.id}><div><div className="status-name">{pilot.name}</div><div className="status-meta">{pilot.team} · {pilot.tasksToday} 项任务</div></div><div className="bar"><span style={{ width: `${Math.min(96, 18 + pilot.workMinutesToday / 7)}%`, background: pilot.workMinutesToday > 500 ? '#d8703f' : undefined }} /></div><div className="status-number">{Math.round(pilot.workMinutesToday / 60)}h</div></div>)}</div></div><div className="panel"><div className="panel-header"><div><div className="panel-title">最近操作</div><div className="panel-kicker">版本和审计实时留痕</div></div></div><div className="panel-body">{data.recentAudits.length ? data.recentAudits.map((item) => <div className="audit-item" key={item.id}><div className="audit-dot" /><div><div className="audit-main">{item.action}</div><div className="audit-time">{item.actor} · {new Date(item.createdAt).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}</div></div></div>) : <div className="empty">还没有操作记录</div>}</div></div></div></section>
  </main>;
}

function Metric({ icon, label, value, note, warn = false }: { icon: React.ReactNode; label: string; value: number; note: string; warn?: boolean }) { return <div className="metric"><div className="metric-top"><span>{label}</span><span className="metric-icon" style={warn ? { color: '#a84e28', background: '#fff0e8' } : undefined}>{icon}</span></div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>; }
